/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _bg_circles_h_
#define _bg_circles_h_
//---------------------------------------------------------------------------------
extern const unsigned char bg_circles[];
extern const int bg_circles_size;
//---------------------------------------------------------------------------------
#endif //_bg_circles_h_
//---------------------------------------------------------------------------------
